version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate2.yaml --s3-bucket b1-photos-album --output-template-file outputTemplate2.yaml
artifacts:
  type: zip
  files:
    - samTemplate2.yaml
    - outputTemplate2.yaml
